server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://34.228.69.160:5432/postgres?currentSchema=financial_institution_new_s&useSSL=false&stringtype=unspecified
    driver-class-name: org.postgresql.Driver
    username: sandeep_j
    password: IPDS6t*#$!49
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: financial_institution_new_s
    hibernate:
      ddl-auto: update
  # Optional: Enable logging for Hibernate SQL queries (useful for debugging)
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
